[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-vdebug/vdebug'
hook_add = '''
let g:vdebug_options= {
\    "port" : 9000,
\    "server" : 'admin.ngo.test',
\    "timeout" : 20,
\    "on_close" : 'detach',
\    "break_on_open" : 1,
\    "ide_key" : 'PHPSTORM',
\    "path_maps" : {},
\    "debug_window_level" : 0,
\    "debug_file_level" : 0,
\    "debug_file" : "",
\    "watch_window_style" : 'expanded',
\    "marker_default" : '⬦',
\    "marker_closed_tree" : '▸',
\    "marker_open_tree" : '▾'
\}
let g:vdebug_options['path_maps'] = {"/home/vagrant/code/front": "~/app/ngo/front"}
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_do_mapping = 0 "Disable default mappings
let g:EasyMotion_space_jump_first = 1
let g:EasyMotion_smartcase = 1
'''

[[plugins]]
repo = 'tyru/caw.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lambdalisue/gina.vim'


[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'cespare/vim-toml'


# colorscheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'morhetz/gruvbox'
